name: CSpell Check

on:
  issue_comment:
    types: [created]

jobs:
  spellcheck:
    if: github.event.issue.pull_request && github.event.comment.body == '/check-ru'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
            [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
            PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
            git fetch origin pull/$PR_NUMBER/head:pr-$PR_NUMBER
            echo "PR_DIFF<<EOF" >> $GITHUB_OUTPUT
            git diff --name-only origin/${{ github.base_ref }} pr-$PR_NUMBER >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            echo "::set-output name=pr_output::$GITHUB_OUTPUT"
        shell: /usr/bin/bash -e {0}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install CSpell and dictionaries
        run: |
          npm install -g cspell
          npm install -g @cspell/dict-ru_ru
          cspell link add @cspell/dict-ru_ru
          npm install -g @cspell/dict-en-common-misspellings
          cspell link add @cspell/dict-en-common-misspellings

      - name: Run CSpell
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.pr_output }}"
          echo "Files to check:"
          echo "$CHANGED_FILES"
          echo "Running CSpell..."		
          CSPELL_OUTPUT=$(cspell --config ./cspell.json --debug $CHANGED_FILES)
          echo "CSpell output:"
          echo "$CSPELL_OUTPUT"
          echo "::set-output name=cspell_output::$CSPELL_OUTPUT"
        id: cspell		
        continue-on-error: true

      - name: Create comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            CSpell output:
            ${{ steps.cspell.outputs.cspell_output }}
