name: CSpell Check

on:
  issue_comment:
    types: [created]

jobs:
  cspell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install CSpell and dictionaries
        run: |
          npm install -g cspell
          npm install -g @cspell/dict-ru_ru
          cspell link add @cspell/dict-ru_ru
          npm install -g @cspell/dict-en-common-misspellings
          cspell link add @cspell/dict-en-common-misspellings

      - name: Download latest SDD dictionary
        run: |
          REPO="AlexJameson/software-development-dictionary-ru"
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/$REPO/releases/latest)
          DOWNLOAD_URL=$(echo $LATEST_RELEASE | grep -o '"browser_download_url": "[^"]*sdd.txt"' | cut -d '"' -f 4)
          if [ -n "$DOWNLOAD_URL" ]; then
              curl -L -o sdd.txt "$DOWNLOAD_URL"
              echo "Downloaded sdd.txt from latest release"
          else
              echo "Error: Could not find sdd.txt in the latest release"
              exit 1
          fi

      - name: Check diff
        run: |
          cspell --config ./cspell.json --show-context

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: github.context.issue.number,
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              body: 'CSpell check result:\n' + github.actions.getCommandOutput('cspell-check')
            })

      - name: Trigger on /check-ru comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = github.context.payload.comment.body;
            if (comment === '/check-ru') {
              github.actions.setCommandOutput('cspell-check', 'true');
            }
